services:
  php:
      build: ./.dev/docker/images/php
      volumes:
        - ./:/data
      depends_on:
          - postgres10
          - postgres17

  postgres10:
    image: postgres:10
    ports:
      - "54310:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schema_keeper

  postgres17:
    image: postgres:17
    ports:
      - "54317:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schema_keeper
